spring:
  datasource:
    username: senderdb
    password: senderdb
    url: jdbc:postgresql://localhost:5432/senderdb
    driver-class-name: org.postgresql.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
        debug: false

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB